package edu.upc.as.data.speedment.showscom.public_.seient_en_representacio.impl;

import com.speedment.Speedment;
import com.speedment.exception.SpeedmentException;
import com.speedment.internal.core.code.AbstractBaseEntity;
import edu.upc.as.data.speedment.showscom.public_.entrada.Entrada;
import edu.upc.as.data.speedment.showscom.public_.seient.Seient;
import edu.upc.as.data.speedment.showscom.public_.seient_en_representacio.SeientEnRepresentacio;

import javax.annotation.Generated;
import java.util.Objects;
import java.util.Optional;
import java.util.StringJoiner;

/**
 * An implementation representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@31c4f311.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public final class SeientEnRepresentacioImpl extends AbstractBaseEntity<SeientEnRepresentacio> implements SeientEnRepresentacio {
    
    private String sessio;
    private String nomlocalrep;
    private String nomlocal;
    private Integer fila;
    private Integer columna;
    private String estat;
    private Integer identificadorentrada;
    
    SeientEnRepresentacioImpl(Speedment speedment) {
        super(speedment);
    }
    
    public SeientEnRepresentacioImpl(Speedment speedment, final SeientEnRepresentacio seientEnRepresentacio) {
        super(speedment);
        setSessio(seientEnRepresentacio.getSessio());
        setNomlocalrep(seientEnRepresentacio.getNomlocalrep());
        setNomlocal(seientEnRepresentacio.getNomlocal());
        setFila(seientEnRepresentacio.getFila());
        setColumna(seientEnRepresentacio.getColumna());
        setEstat(seientEnRepresentacio.getEstat());
        seientEnRepresentacio.getIdentificadorentrada().ifPresent(this::setIdentificadorentrada);
    }
    
    @Override
    public String getSessio() {
        return sessio;
    }
    
    @Override
    public final SeientEnRepresentacioImpl setSessio(String sessio) {
        this.sessio = sessio;
        return this;
    }
    
    @Override
    public String getNomlocalrep() {
        return nomlocalrep;
    }
    
    @Override
    public final SeientEnRepresentacioImpl setNomlocalrep(String nomlocalrep) {
        this.nomlocalrep = nomlocalrep;
        return this;
    }
    
    @Override
    public String getNomlocal() {
        return nomlocal;
    }
    
    @Override
    public final SeientEnRepresentacioImpl setNomlocal(String nomlocal) {
        this.nomlocal = nomlocal;
        return this;
    }
    
    @Override
    public Integer getFila() {
        return fila;
    }
    
    @Override
    public final SeientEnRepresentacioImpl setFila(Integer fila) {
        this.fila = fila;
        return this;
    }
    
    @Override
    public Integer getColumna() {
        return columna;
    }
    
    @Override
    public final SeientEnRepresentacioImpl setColumna(Integer columna) {
        this.columna = columna;
        return this;
    }
    
    @Override
    public String getEstat() {
        return estat;
    }
    
    @Override
    public final SeientEnRepresentacioImpl setEstat(String estat) {
        this.estat = estat;
        return this;
    }
    
    @Override
    public Optional<Integer> getIdentificadorentrada() {
        return Optional.ofNullable(identificadorentrada);
    }
    
    @Override
    public final SeientEnRepresentacioImpl setIdentificadorentrada(Integer identificadorentrada) {
        this.identificadorentrada = identificadorentrada;
        return this;
    }
    
    @Override
    public Seient findFila() {
        return managerOf_(Seient.class).findAny(Seient.FILA, getFila())
            .orElseThrow(() -> new SpeedmentException(
                "Foreign key constraint error. Seient is set to " + getFila()
                ));
            
    }
    
    @Override
    public Optional<Entrada> findIdentificadorentrada() {
        return getIdentificadorentrada()
            .flatMap(identificadorentrada_ -> managerOf_(Entrada.class).findAny(Entrada.IDENTIFICADOR, identificadorentrada_));
    }


    @Override
    public SeientEnRepresentacio copy() {
        return new SeientEnRepresentacioImpl(getSpeedment_(), this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("sessio = "+Objects.toString(getSessio()));
        sj.add("nomlocalrep = "+Objects.toString(getNomlocalrep()));
        sj.add("nomlocal = "+Objects.toString(getNomlocal()));
        sj.add("fila = "+Objects.toString(getFila()));
        sj.add("columna = "+Objects.toString(getColumna()));
        sj.add("estat = "+Objects.toString(getEstat()));
        sj.add("identificadorentrada = "+Objects.toString(getIdentificadorentrada().orElse(null)));
        return "SeientEnRepresentacioImpl "+sj.toString();
    }
    
    @Override
    public boolean equals(Object that) {
        if (this == that) { return true; }
        if (!(that instanceof SeientEnRepresentacio)) { return false; }
        @SuppressWarnings("unchecked")
        final SeientEnRepresentacio thatSeientEnRepresentacio = (SeientEnRepresentacio)that;
        if (!Objects.equals(this.getSessio(), thatSeientEnRepresentacio.getSessio())) {return false; }
        if (!Objects.equals(this.getNomlocalrep(), thatSeientEnRepresentacio.getNomlocalrep())) {return false; }
        if (!Objects.equals(this.getNomlocal(), thatSeientEnRepresentacio.getNomlocal())) {return false; }
        if (!Objects.equals(this.getFila(), thatSeientEnRepresentacio.getFila())) {return false; }
        if (!Objects.equals(this.getColumna(), thatSeientEnRepresentacio.getColumna())) {return false; }
        if (!Objects.equals(this.getEstat(), thatSeientEnRepresentacio.getEstat())) {return false; }
        if (!Objects.equals(this.getIdentificadorentrada(), thatSeientEnRepresentacio.getIdentificadorentrada())) {return false; }
        return true;
    }
    
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(getSessio());
        hash = 31 * hash + Objects.hashCode(getNomlocalrep());
        hash = 31 * hash + Objects.hashCode(getNomlocal());
        hash = 31 * hash + Objects.hashCode(getFila());
        hash = 31 * hash + Objects.hashCode(getColumna());
        hash = 31 * hash + Objects.hashCode(getEstat());
        hash = 31 * hash + Objects.hashCode(getIdentificadorentrada());
        return hash;
    }
    
    @Override
    public Class<SeientEnRepresentacio> getEntityClass_() {
        return SeientEnRepresentacio.class;
    }
}