package edu.upc.as.data.speedment;

import com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle;
import edu.upc.as.data.speedment.showscom.public_.entrada.impl.EntradaManagerImpl;
import edu.upc.as.data.speedment.showscom.public_.espectacle.impl.EspectacleManagerImpl;
import edu.upc.as.data.speedment.showscom.public_.estrena.impl.EstrenaManagerImpl;
import edu.upc.as.data.speedment.showscom.public_.local.impl.LocalManagerImpl;
import edu.upc.as.data.speedment.showscom.public_.representacio.impl.RepresentacioManagerImpl;
import edu.upc.as.data.speedment.showscom.public_.seient.impl.SeientManagerImpl;
import edu.upc.as.data.speedment.showscom.public_.seient_en_representacio.impl.SeientEnRepresentacioManagerImpl;
import edu.upc.as.data.speedment.showscom.public_.sessio.impl.SessioManagerImpl;

import javax.annotation.Generated;

/**
 * A {@link
 * com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle} class
 * for the {@link com.speedment.config.Project} named speedment.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class SpeedmentApplication extends SpeedmentApplicationLifecycle<SpeedmentApplication> {
    
    public SpeedmentApplication() {
        setSpeedmentApplicationMetadata(new SpeedmentApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        super.onInit();
        loadAndSetProject();
        put(new EntradaManagerImpl(speedment));
        put(new EspectacleManagerImpl(speedment));
        put(new EstrenaManagerImpl(speedment));
        put(new LocalManagerImpl(speedment));
        put(new RepresentacioManagerImpl(speedment));
        put(new SeientManagerImpl(speedment));
        put(new SeientEnRepresentacioManagerImpl(speedment));
        put(new SessioManagerImpl(speedment));
    }
}