package edu.upc.as.data.speedment.showscom.public_.entrada;

import com.speedment.Entity;
import com.speedment.field.ComparableField;
import com.speedment.internal.core.field.ComparableFieldImpl;
import edu.upc.as.data.speedment.showscom.public_.representacio.Representacio;
import edu.upc.as.data.speedment.showscom.public_.seient_en_representacio.SeientEnRepresentacio;

import javax.annotation.Generated;
import java.sql.Date;
import java.util.List;
import java.util.stream.Stream;

/**
 * An interface representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@3c4464bf.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface Entrada extends Entity<Entrada> {

    public final static ComparableField<Entrada, Integer> IDENTIFICADOR = new ComparableFieldImpl<>("identificador", Entrada::getIdentificador, Entrada::setIdentificador);
    

    String getDniclient();
    
    Entrada setDniclient(String dniclient);
    
    Integer getNombreespectadors();
    
    Entrada setNombreespectadors(Integer nombreespectadors);
    
    Date getData();
    
    Entrada setData(Date data);
    
    Float getPreu();
    
    Entrada setPreu(Float preu);
    
    String getSessio();
    
    Entrada setSessio(String sessio);
    
    String getNomlocal();
    
    Entrada setNomlocal(String nomlocal);
    
    Integer getIdentificador();

    Entrada setIdentificador(Integer identificador);
    

    Representacio findRepresentacio();

    Stream<SeientEnRepresentacio> findSeientEnRepresentaciosByIdentificadorentrada();
    
    Stream<SeientEnRepresentacio> findSeientEnRepresentacios();

    void setRepresentacioISeients(Representacio r, List<SeientEnRepresentacio> seientsEnR);
}