package edu.upc.as.data.speedment.showscom.public_.sessio;

import com.speedment.Entity;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.StringFieldImpl;
import edu.upc.as.data.speedment.showscom.public_.representacio.Representacio;

import javax.annotation.Generated;
import java.util.stream.Stream;

/**
 * An interface representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@5eada0c6.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface Sessio extends Entity<Sessio> {
    
    /**
     * This Field corresponds to the {@link Sessio} field that can be obtained
     * using the {@link Sessio#getSessio()} method.
     */
    public final static StringField<Sessio> SESSIO = new StringFieldImpl<>("sessio", Sessio::getSessio, Sessio::setSessio);
    
    /**
     * Returns the sessio of this Sessio. The sessio field corresponds to the
     * database column showscom.public.sessio.sessio.
     * 
     * @return the sessio of this Sessio
     */
    String getSessio();
    
    /**
     * Sets the sessio of this Sessio. The sessio field corresponds to the
     * database column showscom.public.sessio.sessio.
     * 
     * @param sessio to set of this Sessio
     * @return this Sessio instance
     */
    Sessio setSessio(String sessio);
    
    /**
     * Creates and returns a {@link Stream} of all {@link Representacio} Entities
     * that references this Entity by the foreign key field that can be obtained
     * using {@link Representacio#getSessio()}. The order of the Entities are
     * undefined and may change from time to time.
     * <p>
     * Using this method, you may "walk the graph" and jump directly between
     * referencing Entities without using {@code JOIN}s.<p> N.B. The current
     * implementation supports lazy-loading of the referencing Entities.
     * 
     * @return a {@link Stream} of all {@link Representacio} Entities that
     * references this Entity by the foreign key field that can be obtained using
     * {@link Representacio#getSessio()}
     */
    Stream<Representacio> findRepresentaciosBySessio();
    
    /**
     * Creates and returns a <em>distinct</em> {@link Stream} of all {@link
     * Representacio} Entities that references this Entity by a foreign key. The
     * order of the Entities are undefined and may change from time to time.
     * <p>
     * Note that the Stream is <em>distinct</em>, meaning that referencing
     * Entities will only appear once in the Stream, even though they may
     * reference this Entity by several columns.
     * <p>
     * Using this method, you may "walk the graph" and jump directly between
     * referencing Entities without using {@code JOIN}s.<p> N.B. The current
     * implementation supports lazy-loading of the referencing Entities.
     * 
     * @return a <em>distinct</em> {@link Stream} of all {@link Representacio}
     * Entities that references this Entity by a foreign key
     */
    Stream<Representacio> findRepresentacios();
}