package edu.upc.as.data.speedment.showscom.public_.seient_en_representacio;

import com.speedment.Entity;
import com.speedment.field.ComparableForeignKeyField;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.ComparableForeignKeyFieldImpl;
import com.speedment.internal.core.field.StringFieldImpl;
import edu.upc.as.data.speedment.showscom.public_.entrada.Entrada;
import edu.upc.as.data.speedment.showscom.public_.seient.Seient;

import javax.annotation.Generated;
import java.util.Optional;

/**
 * An interface representing an entity (for example, a row) in the
 * com.speedment.internal.ui.config.TableProperty@31c4f311.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface SeientEnRepresentacio extends Entity<SeientEnRepresentacio> {
    
    /**
     * This Field corresponds to the {@link SeientEnRepresentacio} field that can
     * be obtained using the {@link SeientEnRepresentacio#getSessio()} method.
     */

    /**
     * This Field corresponds to the {@link SeientEnRepresentacio} field that can
     * be obtained using the {@link SeientEnRepresentacio#getFila()} method.
     */
    public final static ComparableForeignKeyField<SeientEnRepresentacio, Integer, Seient> FILA = new ComparableForeignKeyFieldImpl<>("fila", SeientEnRepresentacio::getFila, SeientEnRepresentacio::setFila, SeientEnRepresentacio::findFila);

    /**
     * This Field corresponds to the {@link SeientEnRepresentacio} field that can
     * be obtained using the {@link SeientEnRepresentacio#getEstat()} method.
     */
    public final static StringField<SeientEnRepresentacio> ESTAT = new StringFieldImpl<>("estat", SeientEnRepresentacio::getEstat, SeientEnRepresentacio::setEstat);
    /**
     * This Field corresponds to the {@link SeientEnRepresentacio} field that can
     * be obtained using the {@link
     * SeientEnRepresentacio#getIdentificadorentrada()} method.
     */
    public final static ComparableForeignKeyField<SeientEnRepresentacio, Integer, Entrada> IDENTIFICADORENTRADA = new ComparableForeignKeyFieldImpl<>("identificadorentrada", o -> o.getIdentificadorentrada().orElse(null), SeientEnRepresentacio::setIdentificadorentrada, fk -> fk.findIdentificadorentrada().orElse(null));
    
    /**
     * Returns the sessio of this SeientEnRepresentacio. The sessio field
     * corresponds to the database column
     * showscom.public.seient_en_representacio.sessio.
     * 
     * @return the sessio of this SeientEnRepresentacio
     */
    String getSessio();
    
    /**
     * Sets the sessio of this SeientEnRepresentacio. The sessio field
     * corresponds to the database column
     * showscom.public.seient_en_representacio.sessio.
     *
     * @param sessio to set of this SeientEnRepresentacio
     * @return this SeientEnRepresentacio instance
     */
    SeientEnRepresentacio setSessio(String sessio);
    
    /**
     * Returns the nomlocalrep of this SeientEnRepresentacio. The nomlocalrep
     * field corresponds to the database column
     * showscom.public.seient_en_representacio.nomlocalrep.
     *
     * @return the nomlocalrep of this SeientEnRepresentacio
     */
    String getNomlocalrep();
    
    /**
     * Sets the nomlocalrep of this SeientEnRepresentacio. The nomlocalrep field
     * corresponds to the database column
     * showscom.public.seient_en_representacio.nomlocalrep.
     *
     * @param nomlocalrep to set of this SeientEnRepresentacio
     * @return this SeientEnRepresentacio instance
     */
    SeientEnRepresentacio setNomlocalrep(String nomlocalrep);
    
    /**
     * Returns the nomlocal of this SeientEnRepresentacio. The nomlocal field
     * corresponds to the database column
     * showscom.public.seient_en_representacio.nomlocal.
     *
     * @return the nomlocal of this SeientEnRepresentacio
     */
    String getNomlocal();
    
    /**
     * Sets the nomlocal of this SeientEnRepresentacio. The nomlocal field
     * corresponds to the database column
     * showscom.public.seient_en_representacio.nomlocal.
     *
     * @param nomlocal to set of this SeientEnRepresentacio
     * @return this SeientEnRepresentacio instance
     */
    SeientEnRepresentacio setNomlocal(String nomlocal);
    
    /**
     * Returns the fila of this SeientEnRepresentacio. The fila field corresponds
     * to the database column showscom.public.seient_en_representacio.fila.
     *
     * @return the fila of this SeientEnRepresentacio
     */
    Integer getFila();
    
    /**
     * Sets the fila of this SeientEnRepresentacio. The fila field corresponds to
     * the database column showscom.public.seient_en_representacio.fila.
     *
     * @param fila to set of this SeientEnRepresentacio
     * @return this SeientEnRepresentacio instance
     */
    SeientEnRepresentacio setFila(Integer fila);
    
    /**
     * Returns the columna of this SeientEnRepresentacio. The columna field
     * corresponds to the database column
     * showscom.public.seient_en_representacio.columna.
     *
     * @return the columna of this SeientEnRepresentacio
     */
    Integer getColumna();
    
    /**
     * Sets the columna of this SeientEnRepresentacio. The columna field
     * corresponds to the database column
     * showscom.public.seient_en_representacio.columna.
     *
     * @param columna to set of this SeientEnRepresentacio
     * @return this SeientEnRepresentacio instance
     */
    SeientEnRepresentacio setColumna(Integer columna);
    
    /**
     * Returns the estat of this SeientEnRepresentacio. The estat field
     * corresponds to the database column
     * showscom.public.seient_en_representacio.estat.
     *
     * @return the estat of this SeientEnRepresentacio
     */
    String getEstat();
    
    /**
     * Sets the estat of this SeientEnRepresentacio. The estat field corresponds
     * to the database column showscom.public.seient_en_representacio.estat.
     *
     * @param estat to set of this SeientEnRepresentacio
     * @return this SeientEnRepresentacio instance
     */
    SeientEnRepresentacio setEstat(String estat);
    
    /**
     * Returns the identificadorentrada of this SeientEnRepresentacio. The
     * identificadorentrada field corresponds to the database column
     * showscom.public.seient_en_representacio.identificadorentrada.
     *
     * @return the identificadorentrada of this SeientEnRepresentacio
     */
    Optional<Integer> getIdentificadorentrada();
    
    /**
     * Sets the identificadorentrada of this SeientEnRepresentacio. The
     * identificadorentrada field corresponds to the database column
     * showscom.public.seient_en_representacio.identificadorentrada.
     * 
     * @param identificadorentrada to set of this SeientEnRepresentacio
     * @return this SeientEnRepresentacio instance
     */
    SeientEnRepresentacio setIdentificadorentrada(Integer identificadorentrada);
    
    /**
     * Finds and returns the foreign key Entity {@link Seient} referenced by the
     * field that can be obtained using {@link
     * SeientEnRepresentacio#getFila()}.<p> N.B. The current implementation only
     * supports lazy-loading of the referenced Entities. This means that if you
     * traverse N SeientEnRepresentacio entities and call this method for each
     * one, there will be N SQL-queries executed.
     * 
     * @return the foreign key Entity {@link Seient} referenced by the field that
     * can be obtained using {@link SeientEnRepresentacio#getFila()}
     */
    Seient findFila();
    
    /**
     * Finds and returns the foreign key Entity {@link Entrada} referenced by the
     * field that can be obtained using {@link
     * SeientEnRepresentacio#getIdentificadorentrada()}.<p> N.B. The current
     * implementation only supports lazy-loading of the referenced Entities. This
     * means that if you traverse N SeientEnRepresentacio entities and call this
     * method for each one, there will be N SQL-queries executed.
     * 
     * @return the foreign key Entity {@link Entrada} referenced by the field
     * that can be obtained using {@link
     * SeientEnRepresentacio#getIdentificadorentrada()}
     */
    Optional<Entrada> findIdentificadorentrada();

}