package edu.upc.as.data.speedment.showscom.public_.estrena.impl;

import com.speedment.Speedment;
import com.speedment.config.Column;
import com.speedment.config.Table;
import com.speedment.config.mapper.TypeMapper;
import com.speedment.exception.SpeedmentException;
import com.speedment.internal.core.config.mapper.identity.IntegerIdentityMapper;
import com.speedment.internal.core.config.mapper.identity.StringIdentityMapper;
import com.speedment.internal.core.manager.sql.AbstractSqlManager;
import edu.upc.as.data.speedment.showscom.public_.estrena.Estrena;

import javax.annotation.Generated;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;

/**
 * A manager implementation representing an entity (for example, a row) in
 * the com.speedment.internal.ui.config.TableProperty@516db050.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class EstrenaManagerImpl extends AbstractSqlManager<Estrena> {
    
    private final TypeMapper<String, String> nomlocalTypeMapper = new StringIdentityMapper();
    private final TypeMapper<String, String> sessioTypeMapper = new StringIdentityMapper();
    private final TypeMapper<Integer, Integer> recarrecTypeMapper = new IntegerIdentityMapper();
    
    public EstrenaManagerImpl(Speedment speedment) {
        super(speedment);
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public Class<Estrena> getEntityClass() {
        return Estrena.class;
    }
    
    @Override
    public Object get(Estrena entity, Column column) {
        switch (column.getName()) {
            case "nomlocal" : return entity.getNomlocal();
            case "sessio" : return entity.getSessio();
            case "recarrec" : return entity.getRecarrec();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    public void set(Estrena entity, Column column, Object value) {
        switch (column.getName()) {
            case "nomlocal" : entity.setNomlocal((String) value); break;
            case "sessio" : entity.setSessio((String) value); break;
            case "recarrec" : entity.setRecarrec((Integer) value); break;
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    public Table getTable() {
        return speedment.getProjectComponent().getProject().findTableByName("showscom.public.estrena");
    }
    
    protected Estrena defaultReadEntity(ResultSet resultSet) {
        final Estrena entity = newInstance();
        try {
            entity.setNomlocal(nomlocalTypeMapper.toJavaType(resultSet.getString(1)));
            entity.setSessio(sessioTypeMapper.toJavaType(resultSet.getString(2)));
            entity.setRecarrec(recarrecTypeMapper.toJavaType(resultSet.getInt(3)));
        }
        catch (SQLException sqle) {
            throw new SpeedmentException(sqle);
        }
        return entity;
    }
    
    @Override
    public Estrena newInstance() {
        return new EstrenaImpl(speedment);
    }
    
    @Override
    public List<String> primaryKeyFor(Estrena entity) {
        return Arrays.asList(entity.getNomlocal(), entity.getSessio());
    }
}